FROM php:7.1-apache

# installing required stuff
RUN apt-get update
RUN apt-get install -y unzip git

# PHP extensions
RUN \
    docker-php-ext-configure pdo_mysql --with-pdo-mysql=mysqlnd \
    && docker-php-ext-configure mysqli --with-mysqli=mysqlnd \
    && docker-php-ext-install pdo_mysql

# Apache configuration for mod-rewrite
RUN a2enmod rewrite
RUN service apache2 restart
